name: hol-github

services:
  db:
    container_name: db
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    entrypoint: docker-entrypoint.sh -c 'shared_buffers=256MB' -c 'max_connections=200'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 3001:80
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin:
