openapi: 3.0.3
info:
  title: API
  version: 1.0.0
paths:
  /api/game/new:
    post:
      summary: Start a new game
      responses:
        200:
          description: OK
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  gameId:
                    type: string
                  firstImage:
                    type: string
                    format: binary
                  secondImage:
                    type: string
                    format: binary
                  repos:
                    type: object
                    properties:
                      first:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                      second:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string

  /api/game/choose:
    post:
      summary: Submit choice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gameId:
                  type: string
                choice:
                  type: string
                  enum: [ higher, lower ]
      responses:
        404:
          description: Game with provided id doesn't exist
        200:
          description: OK
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum: [ correct, wrong ]
                  next:
                    type: object
                    properties:
                      image:
                        type: string
                        format: binary
                      repo:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string

  /api/user/signup:
    post:
      summary: Sign up a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 1
                password:
                  type: string
                  pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$'
      responses:
        200:
          description: OK
        409:
          description: Username already exists
        400:
          description: Wrong format of username or password

  /api/user/signin:
    post:
      summary: Sign in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  minLength: 1
                  type: string
                password:
                  minLength: 1
                  type: string
      responses:
        200:
          description: OK
        400:
          description: Wrong format of username or password
        401:
          description: Invalid username or password

  /api/user/signout:
    post:
      summary: Sign out
      responses:
        200:
          description: OK
        401:
          description: User not logged in